"""empty message

Revision ID: 00e693512343
Revises: 7c7df5f43222
Create Date: 2021-05-09 19:11:03.169880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e693512343'
down_revision = '7c7df5f43222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_users', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'price')
    op.drop_column('test_users', 'price')
    # ### end Alembic commands ###
