"""empty message

Revision ID: 1e5532fa8540
Revises: 00e693512343
Create Date: 2021-05-10 11:48:00.883926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5532fa8540'
down_revision = '00e693512343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('deliveries', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('deliveries', sa.Column('detail_address', sa.String(length=255), nullable=True))
    op.add_column('deliveries', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('deliveries', sa.Column('username', sa.String(length=20), nullable=True))
    op.add_column('test_deliveries', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('test_deliveries', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('test_deliveries', sa.Column('detail_address', sa.String(length=255), nullable=True))
    op.add_column('test_deliveries', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('test_deliveries', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_deliveries', 'username')
    op.drop_column('test_deliveries', 'phone')
    op.drop_column('test_deliveries', 'detail_address')
    op.drop_column('test_deliveries', 'created_at')
    op.drop_column('test_deliveries', 'address')
    op.drop_column('deliveries', 'username')
    op.drop_column('deliveries', 'phone')
    op.drop_column('deliveries', 'detail_address')
    op.drop_column('deliveries', 'created_at')
    op.drop_column('deliveries', 'address')
    # ### end Alembic commands ###
