"""empty message

Revision ID: 7c7df5f43222
Revises: f77f48004d2f
Create Date: 2021-05-09 01:21:56.691365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7df5f43222'
down_revision = 'f77f48004d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('test_products', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_products', 'image_url')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
