"""empty message

Revision ID: c31d77a17116
Revises: 59a16b6c33b9
Create Date: 2021-05-09 00:52:20.565521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31d77a17116'
down_revision = '59a16b6c33b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'test_categories', ['category_id'], ['id'])
    op.add_column('test_products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_products', 'test_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_products', type_='foreignkey')
    op.drop_column('test_products', 'category_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
